/**
 * La sezione dei visti di un bando CNR vero, come l'aveva salvata il vecchio
 * editor: una riga del PDF per capoverso (riscontro del 2026-10-02 sulla
 * versione 36 del server di test). Serve a provare "Unisci righe" e i fogli.
 */
export const RIGHE_VISTI: string[] = [
  'IL VICEPRESIDENTE',
  'VISTO il D.Lgs 4 giugno 2003, n. 127 "Riordino del Consiglio Nazionale delle Ricerche”;',
  'VISTO il D.Lgs 31 dicembre 2009 n. 213, “Riordino degli Enti di ricerca in attuazione dell’art. 1 della',
  'legge 27 settembre 2007, n. 165”;',
  'VISTO il D.Lgs 25 novembre 2016, n. 218 recante “Semplificazione delle attività degli Enti Pubblici',
  "di Ricerca ai sensi dell'articolo 13 della legge 7 agosto 2015, n. 124”;",
  'VISTO lo Statuto del CNR, emanato con provvedimento del Presidente del CNR n. 93 prot.',
  '0051080/2018 del 19/07/2018, di cui è stato dato l’avviso di pubblicazione sul sito del Ministero',
  'dell’Istruzione, dell’Università e della Ricerca in data 25 luglio 2018, entrato in vigore il 1° agosto',
  '2018;',
  'VISTO il Regolamento di Organizzazione e Funzionamento del CNR, emanato con provvedimento',
  'della Presidente del CNR n. 119, prot. n. 0241776 del 10 luglio 2024, pubblicato sul sito istituzionale',
  'del Consiglio Nazionale delle Ricerche e del Ministero dell’Istruzione dell’Università e della Ricerca,',
  'entrato in vigore il 1° agosto 2024;',
  'VISTO il Regolamento del Personale del CNR, emanato con decreto del Presidente del CNR prot. n.',
  '0025035 in data 4 maggio 2005, pubblicato nel Supplemento ordinario n. 101 alla Gazzetta Ufficiale',
  'della Repubblica Italiana n. 124 del 30 maggio 2005;',
  'VISTA la Legge 7 agosto 1990, n. 241, “Nuove norme in materia di procedimento amministrativo e di',
  'diritto d’accesso ai documenti amministrativi”, e successive modificazioni;',
  'VISTO il D.P.R. 12 febbraio 1991, n.171, per le parti compatibili;',
  'VISTO il D.P.R. 9 maggio 1994, n. 487 e successive modifiche e integrazioni “Regolamento recante',
  'norme sull’accesso agli impieghi nelle pubbliche amministrazioni e le modalità di svolgimento dei',
  'concorsi, dei concorsi unici e delle altre assunzioni nei pubblici impieghi” come modificato e integrato',
  'dal D.P.R n. 82 del 16 giugno 2023;',
  'VISTA la legge 5 febbraio 1992 n. 104, “Legge quadro per l’assistenza, l’integrazione sociale e i diritti',
  'delle persone handicappate”;',
  'VISTA la Legge 12 marzo 1999, n. 68 “Norme per il diritto al lavoro dei disabili” e successive',
  'modificazioni ed integrazioni;',
  'VISTO il D.P.R. 10 ottobre 2000, n. 333, "Regolamento di esecuzione della Legge 12 marzo 1999, n.',
  '68, recante norme per il diritto al lavoro dei disabili ";',
  'VISTO il D.P.R. 28 dicembre 2000, n. 445 “Testo unico delle disposizioni legislative e regolamentari',
  'in materia di documentazione amministrativa” e successive modificazioni;',
  'VISTO il D.Lgs 30 marzo 2001, n. 165 concernente “Norme generali sull’ordinamento del lavoro alle',
  'dipendenze delle amministrazioni pubbliche” e successive modificazioni ed in particolare l’art. 35 c. 5',
  'bis concernente la permanenza nella sede di prima destinazione, l’art. 35 bis inserito dall’art. 1 comma',
  '146 della Legge 6 novembre 2012 n. 190, rubricato “Prevenzione del fenomeno della corruzione nella',
  'formazione di commissioni e nelle assegnazioni degli uffici” nonché l’art. 38, così come modificato',
  'dall’art. 7 della legge n. 97 del 6 agosto 2013 e l’art. 57 “Pari opportunità;',
  'VISTO in particolare l’art.35 quater c.1 del D.lgs. n.165 del 30 marzo 2001 il quale stabilisce che le',
  'prove di esame sono finalizzate ad accertare il possesso delle competenze, intese come insieme delle',
  'conoscenze e delle capacità logico-tecniche, comportamentali nonché manageriali, per i profili che',
  'svolgono tali compiti, che devono essere specificate nel bando e definite in maniera coerente con la',
  "natura dell'impiego, ovvero delle abilità residue nel caso dei soggetti di cui all'articolo 1, comma 1, della",
  'legge 12 marzo 1999, n. 68.',
  'VISTO inoltre che il medesimo articolo prevede che per profili iniziali e non specializzati, le prove di',
  "esame danno particolare rilievo all'accertamento delle capacità comportamentali, incluse quelle",
  'relazionali, e delle attitudini;',
  'VISTO inoltre l’art. 7, comma 8, del D.P.R. n. 487/1994, come modificato dal D.P.R. n. 82/2023,',
  'stabilisce che “per profili iniziali e non specializzati, le prove di esame danno particolare rilievo',
  'all’accertamento delle capacità comportamentali, incluse quelle relazionali, e delle attitudini e sono',
  'finalizzate ad accertare il possesso delle competenze, intese come insieme delle conoscenze e delle',
  'capacità logico-tecniche, comportamentali nonché manageriali, per i profili che svolgono tali compiti.',
  'Tali prove devono essere specificate nel bando e definite in maniera coerente con la natura',
  'dell’impiego…”;',
  'VISTO il D.Lgs 30 giugno 2003, n. 196 “Codice in materia di protezione dei dati personali” e',
  'successive modificazioni; per le parti compatibili con il sottoindicato Regolamento UE 2016/679;',
  'VISTO il D.Lgs 7 marzo 2005, n. 82 “Codice dell’amministrazione digitale” e successive modifiche e',
  'integrazioni;',
  'VISTO il D.Lgs 11 aprile 2006, n. 198 “Codice delle pari opportunità tra uomo e donna”, come',
  'modificato dal D.Lgs 25 gennaio 2010 n. 5, in attuazione della direttiva 2006/54/CE;',
  'VISTA la Legge 18 giugno 2009, n. 69 ed in particolare l’art. 32, c. 1 concernente l’eliminazione degli',
  'sprechi relativi al mantenimento di documenti in forma cartacea;',
  'VISTO il D.Lgs 27 ottobre 2009, n. 150 “Attuazione della legge 4 marzo 2009, n. 15, in materia di',
  'ottimizzazione della produttività del lavoro pubblico e di efficienza e trasparenza delle pubbliche',
  'amministrazioni”;',
  'VISTO il D.Lgs 15 marzo 2010, n. 66 “Codice dell’ordinamento militare”, come modificato dal D.Lgs',
  '31 dicembre 2012, n. 248, concernente le riserve di posti nei concorsi pubblici in favore dei militari',
  'volontari delle Forze Armate;',
  'VISTA la direttiva del Ministro della pubblica amministrazione e della semplificazione n. 14/2011 per',
  'l’applicazione delle nuove disposizioni in materia di certificati e dichiarazioni sostitutive di cui all’art.',
  '15, della legge 12 novembre 2011, n. 183;',
  'VISTO il D.L. 9 febbraio 2012, n. 5, convertito con modificazioni in Legge n. 35 del 4 aprile 2012',
  '“Disposizioni urgenti in materia di semplificazione e di sviluppo” ed in particolare l’art. 8 c. 1;',
  'VISTO il D.Lgs 14 marzo 2013, n. 33 “Riordino della disciplina riguardante il diritto di accesso civico',
  'e gli obblighi di pubblicità, trasparenza e diffusione di informazioni da parte delle pubbliche',
  'amministrazioni”;',
  'VISTO il Regolamento (UE) 2016/679 del Parlamento europeo e del Consiglio, del 27 aprile 2016,',
  'relativo alla protezione delle persone fisiche con riguardo al trattamento dei dati personali, nonché alla',
  'libera circolazione di tali dati e che abroga la direttiva 95/46/CE (regolamento generale sulla protezione',
  '2dei dati), pubblicato sulla Gazzetta Ufficiale Europea del 4 maggio 2016 ed applicabile a decorrere dal',
  '25 maggio 2018;',
  'VISTO il Decreto Legislativo 25 maggio 2016, n. 97 “Revisione e semplificazione delle disposizioni',
  'in materia di prevenzione della corruzione, pubblicità e trasparenza correttivo della legge 6 novembre',
  '2012, n. 190 e del Decreto Legislativo 14 marzo 2013, n. 33, ai sensi dell’art. 7 della legge 7 agosto',
  '2015, n. 124, in materia di riorganizzazione delle amministrazioni pubbliche”;',
  'VISTO il CCNL del Comparto “Istruzione e Ricerca” 2016 -2018, sottoscritto in data 19 aprile 2018;',
  'VISTO il CCNL relativo al personale del Comparto “Istruzione e Ricerca”, triennio 2019-2021,',
  'sottoscritto in data 6 dicembre 2022, per la parte economica;',
  'VISTO il CCNL del Comparto “Istruzione e Ricerca” 2016 -2018, sottoscritto in data 19 aprile 2018 e',
  'il CCNL del Comparto “Istruzione e Ricerca” 2019-2021, sottoscritto in data 18 gennaio 2024;',
  'CONSIDERATO che, ai sensi dell’art. 5, commi 1 e 2, del D.P.R. 487/94 le riserve dei posti, previste',
  'da leggi speciali a favore di determinate categorie di cittadini, non possono complessivamente superare',
  'la metà dei posti messi a concorso, ivi comprese le riserve in favore del personale interno;',
  'VISTO l’art. 1014, comma 4 del D.Lgs 66/2010 “Codice dell’Ordinamento Militare” concernente le',
  'riserve a favore dei volontari in ferma breve e ferma prefissata delle Forze armate congedati senza',
  'demerito ovvero durante il periodo di rafferma nonché dei volontari in servizio permanente;',
  'ACCERTATO che il 30% dei posti a concorso deve essere prioritariamente riservato ai volontari delle',
  'FF.AA. ai sensi dell’art. 1014, commi 1 e 3 del D.lgs. n. 66/2010;',
  'VISTO l’art. 18 comma 4 del D.Lgs n. 40/2017, come modificato dal d.l. 22 aprile 2023 n. 44,',
  'convertito con modificazioni con Legge 21 giugno 2023 n. 74, che prevede la riserva del 15% dei posti',
  'a favore degli operatori volontari che hanno concluso il servizio civile universale senza demerito;',
  'VISTA la Legge 21 febbraio 2025, n. 15 , di conversione con modificazioni del D.L. 27 dicembre 2024',
  "56/2019, in base al quale le procedure concorsuali bandite dalle pubbliche amministrazioni di cui all'art.",
  '1, comma 2, del decreto legislativo 30 marzo 2001, n. 165, e le conseguenti assunzioni posso essere',
  'effettuate senza il previo svolgimento delle procedure di cui all’art. 30 del D.Lgs 165/2001;',
  'CONSIDERATO che le posizioni lavorative per il profilo di Collaboratore Tecnico Enti di Ricerca,',
  'VI livello professionale di cui al presente bando sono previste nella programmazione del fabbisogno',
  'del personale del piano 2024-2026, già approvata dal Consiglio d’Amministrazione del CNR in data',
  '19 dicembre 2023;',
  'VISTO il provvedimento del Direttore Generale prot. n. 17486 del 22 gennaio 2025 e successiva',
  'rettifica prot. n. 70243 del 10 marzo 2025 relativo all’assegnazione di complessive 91 posizioni riferite',
  'al profilo di Collaboratore Tecnico Enti di Ricerca VI livello professionale;',
  'VISTA la nota prot. n. 263793 dell’11 luglio 2025 rettificata con prot. n. 270168 del 16 luglio 2025',
  'trasmessa al Dipartimento della Funzione pubblica, concernente la comunicazione preventiva ai sensi',
  'dell’art. 34 bis del D.Lgs 165/2001;',
  'TENUTO CONTO che l’assunzione delle unità di personale messa a concorso è condizionata dall’esito',
  'della suddetta procedura di mobilità obbligatoria ex art. 34 bis del D.Lgs 165/2001,',
];
