/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/contesti": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contesti autorizzati alla gestione modelli, anche senza integrazioni connesse */
        get: operations["listaContestiBuilder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tipi-documento/{codiceTipoDocumento}/struttura-disponibile": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codiceTipoDocumento: components["parameters"]["CodiceTipoDocumento"];
            };
            cookie?: never;
        };
        /**
         * Struttura discovery del tipo documento gia' associato a un'integrazione
         * @description Risolve l'integrazione dal codice_contesto di TipoDocumento (non richiede di conoscere l'integrazioneId, a differenza delle route /builder/integrazioni/* di integrazioni-api.openapi.yaml). Nessun import DB, sempre letto live.
         */
        get: operations["getStrutturaDisponibile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modelli": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Modelli e versioni del contesto autorizzato, comprese bozze
         * @description Ordinati per creazione decrescente e id. Non richiede discovery online. Nessuna URL amministrativa esposta.
         */
        get: operations["listaModelliBuilder"];
        put?: never;
        /**
         * Crea un modello in BOZZA a partire da un percorso o categoria/tipologia risolti in discovery
         * @description Autorizzazione per il singolo contesto del tipo documento target (verify_scrittura_su_contesto), mai sull'unione dei contesti del token.
         */
        post: operations["creaModello"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tipi-documento/{codiceTipoDocumento}/policy-dimensioni": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codiceTipoDocumento: components["parameters"]["CodiceTipoDocumento"];
            };
            cookie?: never;
        };
        /**
         * Policy registrate e dimensioni ancora prive di policy
         * @description DEC-002-POLICY. Dichiara, per nome di dimensione della categorizzazione, se ammette un valore generico (un solo modello copre tutti i valori) o se ogni valore identifica un modello distinto, come gia' accade per la lingua. Esplicitamente scollegata da DefinizioneStruttura di `010`, che e' solo l'esempio presentazionale per il team dell'integrazione. `dimensioni_non_configurate` alimenta la segnalazione della schermata 4a: NodoDiscovery ha extra="allow", quindi senza questo elenco una dimensione nuova sparirebbe in silenzio.
         */
        get: operations["getPolicyDimensioni"];
        /**
         * Registra o aggiorna la policy di una dimensione
         * @description Una riga sola per (tipo documento, nome dimensione): la policy vale ovunque quel nome ricompaia nell'albero, mai per singola foglia. Una dimensione la cui persistenza non ammette un valore assente viene rifiutata con GENERICO_NON_SUPPORTATO invece di essere accettata e poi salvata con un valore arbitrario.
         */
        put: operations["setPolicyDimensione"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modelli/filtri": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Valori selezionabili nei filtri dell'elenco modelli
         * @description Ricavati dai modelli esistenti nel contesto, non dall'albero discovery: l'elenco modelli non richiede discovery online e non deve iniziare a dipenderne per riempire delle tendine. Ogni voce restituita produce almeno un risultato. Il livello generico compare come TUTTI.
         */
        get: operations["vociFiltriModelli"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modelli/{modelloId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelloId: components["parameters"]["ModelloId"];
            };
            cookie?: never;
        };
        /**
         * Dettaglio modello con il contratto dati, leggibile anche su una BOZZA
         * @description Alimenta l'anteprima del modello nel builder (schermata 2b in versione ridotta, 007). A differenza di /catalogo/modelli/{modelloVersioneId}/campi-richiesti, che risponde solo su versioni pubblicate, qui i campi sono leggibili anche su una versione in BOZZA. Stesso isolamento per contesto della lista.
         */
        get: operations["getModelloDettaglio"];
        put?: never;
        post?: never;
        /** Elimina logicamente un modello conservando versioni, audit e PDF */
        delete: operations["eliminaModello"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modelli/{modelloId}/varianti": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelloId: components["parameters"]["ModelloId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crea una variante dello stesso modello sulla stessa categorizzazione
         * @description Eredita tipo, percorso e dimensioni dal modello di origine: si indica solo in cosa differisce. Il codice di variante (STANDARD, VARIANTE_1, VARIANTE_2...) lo assegna il sistema. Distinta da edizioni-derivate, che cambia il valore di una dimensione e non la variante.
         */
        post: operations["creaVariante"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modelli/{modelloId}/edizioni-derivate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelloId: components["parameters"]["ModelloId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crea un modello collegato in un'altra lingua clonando l'ultima versione
         * @description Mantiene tipo, percorso, variante e livello del padre. Crea atomicamente un modello indipendente e la sua versione 1 BOZZA copiando formato, struttura e campi richiesti dall'ultima versione del padre. Non pubblica il derivato e non modifica il padre.
         */
        post: operations["creaEdizioneDerivata"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modelli/{modelloId}/versioni": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelloId: components["parameters"]["ModelloId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crea la versione 1 in BOZZA, campi scelti dalla foglia discovery del modello
         * @description I campi devono appartenere al ramo/foglia gia' selezionato dal modello in discovery corrente (rifetch aggiornato); nessun campo non ammesso o duplicato.
         */
        post: operations["creaVersione"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modelli/{modelloId}/versioni/{versioneId}/invia-revisione": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelloId: components["parameters"]["ModelloId"];
                versioneId: components["parameters"]["VersioneId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transizione BOZZA -> IN_REVISIONE */
        post: operations["inviaRevisione"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modelli/{modelloId}/versioni/{versioneId}/approva": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelloId: components["parameters"]["ModelloId"];
                versioneId: components["parameters"]["VersioneId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transizione IN_REVISIONE -> APPROVATO */
        post: operations["approvaVersione"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modelli/{modelloId}/versioni/{versioneId}/pubblica": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelloId: components["parameters"]["ModelloId"];
                versioneId: components["parameters"]["VersioneId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transizione APPROVATO -> PUBBLICATO
         * @description Archivia automaticamente la precedente versione corrente della stessa variante, se presente (non restituita in risposta - rileggere il catalogo per confermarlo).
         */
        post: operations["pubblicaVersione"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modelli/{modelloId}/versioni/{versioneId}/sospendi": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelloId: components["parameters"]["ModelloId"];
                versioneId: components["parameters"]["VersioneId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transizione PUBBLICATO -> SOSPESO
         * @description Da SOSPESO si puo' solo archiviare: la sospensione non e' una pausa da cui si torna indietro.
         */
        post: operations["sospendiVersione"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modelli/{modelloId}/versioni/{versioneId}/archivia": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelloId: components["parameters"]["ModelloId"];
                versioneId: components["parameters"]["VersioneId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transizione PUBBLICATO o SOSPESO -> ARCHIVIATO
         * @description Ritira la versione dal catalogo come scelta esplicita. Prima esisteva solo come effetto collaterale della pubblicazione di un'altra versione sullo stesso slot.
         */
        post: operations["archiviaVersione"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        VociFiltriModelli: {
            codici_tipo_documento: string[];
            codici_tipologia: string[];
            codici_categoria: string[];
            lingue: string[];
            livelli_professionali: string[];
            varianti: string[];
        };
        ModelloGestione: {
            /** Format: uuid */
            id: string;
            public_id: number | null;
            codice: string;
            nome: string;
            codice_tipo_documento: string;
            codice_categoria: string;
            codice_tipologia: string | null;
            percorso_categorizzazione: string[];
            variante: string;
            dimensioni: {
                [key: string]: string;
            };
            /** @enum {string|null} */
            lingua: "IT" | "EN" | null;
            livello_professionale: string | null;
            /** Format: uuid */
            derivato_da_modello_id?: string | null;
            /** @description Descrizione della variante scritta dal gestore; null sul modello standard. */
            nota?: string | null;
            codice_contesto: string;
            /** Format: uuid */
            integrazione_id: string | null;
            /** Format: date-time */
            created_at: string;
            versioni: components["schemas"]["Versione"][];
        };
        PolicyDimensioneRequest: {
            nome_dimensione: string;
            consente_valore_generico: boolean;
            valore_default?: string | null;
        };
        PolicyDimensione: {
            nome_dimensione: string;
            consente_valore_generico: boolean;
            valore_default: string | null;
            modelli_pubblicati_che_la_valorizzano: number;
        };
        DimensioneNonConfigurata: {
            nome_dimensione: string;
            motivo: string;
            modelli_pubblicati_che_la_valorizzano: number;
        };
        PolicyDimensioni: {
            codice_tipo_documento: string;
            policy: components["schemas"]["PolicyDimensione"][];
            dimensioni_non_configurate: components["schemas"]["DimensioneNonConfigurata"][];
        };
        /** @description Il campo come lo legge l'anteprima del builder: metadati completi, a differenza di CampoVersione che e' la forma di richiesta alla creazione. */
        CampoContratto: {
            codice: string;
            etichetta: string;
            tipo: string;
            /** @enum {string} */
            lingua: "IT" | "EN";
            obbligatorio: boolean;
            ordine: number;
            descrizione?: string | null;
        };
        VersioneDettaglio: components["schemas"]["Versione"] & {
            campi: components["schemas"]["CampoContratto"][];
        };
        ModelloDettaglio: {
            /** Format: uuid */
            id: string;
            public_id: number | null;
            codice: string;
            nome: string;
            codice_tipo_documento: string;
            codice_categoria: string;
            codice_tipologia: string | null;
            percorso_categorizzazione: string[];
            variante: string;
            dimensioni: {
                [key: string]: string;
            };
            /** @enum {string|null} */
            lingua: "IT" | "EN" | null;
            livello_professionale: string | null;
            /** Format: uuid */
            derivato_da_modello_id?: string | null;
            /** @description Descrizione della variante scritta dal gestore; null sul modello standard. */
            nota?: string | null;
            codice_contesto: string;
            /** Format: uuid */
            integrazione_id: string | null;
            /** Format: date-time */
            created_at: string;
            /** @description Dimensioni salvate sul modello ma non piu' dichiarate dalla foglia live. */
            dimensioni_non_disponibili: string[];
            versioni: components["schemas"]["VersioneDettaglio"][];
        };
        /** @description percorso_categorizzazione XOR codice_categoria (+ codice_tipologia opzionale se il percorso e' altrimenti ambiguo) - vedi verifica_selezione in backend/app/builder/schemas.py. */
        CreaModelloRequest: {
            codice_tipo_documento: string;
            /**
             * Format: uuid
             * @description Integrazione selezionata; risolve il tipo per sorgente e codice, senza fallback legacy. Omettere solo per chiamate legacy non ambigue.
             */
            integrazione_id?: string;
            percorso_categorizzazione?: string[] | null;
            codice_categoria?: string | null;
            codice_tipologia?: string | null;
            /** @default {} */
            dimensioni: {
                [key: string]: string;
            };
            /** @enum {string} */
            lingua?: "IT" | "EN";
            /** @description Valore dichiarato in livelli_possibili; null significa tutti i livelli della foglia. */
            livello_professionale?: string | null;
            /** @description In cosa questo modello differisce dagli altri sulla stessa categorizzazione (FR-019). Obbligatoria quando la categorizzazione e' gia' occupata: senza, la creazione risponde 409 MODELLO_VARIANTE_RICHIESTA indicando quale modello la occupa. Il codice di variante lo genera il sistema, non il chiamante. */
            nota?: string | null;
        };
        CreaVarianteRequest: {
            nota: string;
        };
        CreaEdizioneDerivataRequest: {
            /** @enum {string} */
            lingua: "IT" | "EN";
        };
        Modello: {
            /** Format: uuid */
            id: string;
            public_id: number | null;
            codice: string;
            nome: string;
            codice_tipo_documento: string;
            codice_categoria: string;
            codice_tipologia: string | null;
            percorso_categorizzazione: string[];
            variante: string;
            /** @enum {string} */
            lingua: "IT" | "EN";
            livello_professionale: string | null;
            /** Format: uuid */
            derivato_da_modello_id?: string | null;
            /** @description Descrizione della variante scritta dal gestore; null sul modello standard. */
            nota?: string | null;
        };
        CreaVersioneRequest: {
            campi: components["schemas"]["CampoVersione"][];
        };
        CampoVersione: {
            codice: string;
            /** @default IT */
            lingua: string;
        };
        Versione: {
            /** Format: uuid */
            id: string;
            public_id: number | null;
            /** Format: uuid */
            modello_id: string;
            numero_versione: number;
            /** @enum {string} */
            stato: "BOZZA" | "IN_REVISIONE" | "APPROVATO" | "PUBBLICATO" | "ARCHIVIATO" | "SOSPESO";
            /** Format: date-time */
            pubblicato_at: string | null;
        };
        Errore: {
            codice: string;
            messaggio: string;
        };
        /** @description Un nodo dell'albero, a qualunque livello. Ha SEMPRE `codice` e `descrizione`; ha POI o `figli` (per scendere di un altro livello, stesso schema ricorsivo) o `campi` (se e' un nodo foglia) - mai entrambi, mai nessuno dei due. Il numero di livelli non e' fissato dal contratto: per `BANDO_CONCORSO` sono due (tipologia, poi profilo), un altro tipo documento potrebbe averne uno solo, tre o piu' - vedi il secondo esempio (`ALTRO_TIPO_DOCUMENTO_ESEMPIO`, tre livelli) qui sopra. `figli`/`campi` restano le uniche chiavi strutturali fisse (necessarie per un parsing ricorsivo deterministico lato GEMODO, indipendentemente da quanti livelli ci sono); il nome concettuale di ciascun livello (tipologia, profilo, o qualunque cosa abbia senso per il vostro dominio) e' invece libero e va nel campo `tipo_livello` sotto - puramente informativo, non usato per il parsing. */
        NodoCategorizzazione: {
            /** @example TD */
            codice: string;
            /** @example Tempo Determinato */
            descrizione: string;
            /** @description Nome del livello di categorizzazione a cui appartiene questo nodo (es. `"tipologia"`, `"profilo"`, o un nome del vostro dominio). Puramente informativo/leggibile per chi consulta la risposta - GEMODO non lo usa per decidere come camminare l'albero (quello dipende solo da `figli`/`campi`). Opzionale. */
            tipo_livello?: string | null;
            /**
             * @description Attributo profilo-dipendente (generalizza il caso "livello", vedi `Attributo Profilo` in `specs/010-configurazione-cataloghi-integrazioni/spec.md`). Opzionale, ha senso solo su un nodo foglia (con `campi`).
             * @example [
             *       "I",
             *       "II",
             *       "III"
             *     ]
             */
            livelli_possibili?: string[];
            /**
             * @description Valore di default fra `livelli_possibili` per questo nodo, se presente.
             * @example III
             */
            livello_base?: string;
            /**
             * @description Lingue dei modelli creabili sulla foglia. **Opzionale** (0.6.0, spec 011): un tipo documento che non distingue i modelli per lingua semplicemente non dichiara questa chiave, e GEMODO non gliene attribuisce una implicita. Fino alla 0.5.0 era obbligatoria sui nodi con `campi`, e una foglia priva di lingua rendeva non conforme l'intera risposta. E' un rilassamento: ogni albero valido con la 0.5.0 resta valido, nessuna integrazione deve cambiare nulla. Resta assente sui nodi intermedi. Non filtra i campi: ogni modello conserva l'intero contratto della foglia.
             * @example [
             *       "IT",
             *       "EN"
             *     ]
             */
            lingue_possibili?: ("IT" | "EN")[];
            /** @description Sotto-nodi, se questo non e' un livello foglia. Un array vuoto e' valido (nodo senza sotto-categorizzazione ancora definita) ma MUST essere compilato prima dell'uso in produzione, non lasciato vuoto silenziosamente. */
            figli?: components["schemas"]["NodoCategorizzazione"][];
            /** @description Campi del contratto dati, presenti solo se questo e' un nodo foglia (nessun `figli`). Se, come nel caso reale di BANDO_CONCORSO, gli stessi campi si ripetono identici su piu' foglie, e' una scelta legittima ripeterli qui uguali - questo contratto non impone un meccanismo di riuso, descrive solo la forma della risposta. */
            campi?: components["schemas"]["CampoContrattoDati"][];
        };
        /** @description Struttura FISSA per ogni campo, identica a qualunque livello dell'albero e per qualunque tipo documento - e' l'unica parte di questo contratto che non cambia mai. */
        CampoContrattoDati: {
            /** @example numero_posti */
            codice: string;
            /** @example Numero posti */
            etichetta: string;
            /**
             * @description Stesso vocabolario di `ModelloCampoRichiesto.tipo_dato` (`001`/`002`): `string`, `number`, `date`, `boolean`, `array`, `object`. Nessun tipo `enum` dedicato - un campo con opzioni vincolate (fisse o dipendenti dal profilo) resta `string`/ `number` con il vincolo espresso in `validazione`.
             * @enum {string}
             */
            tipo: "string" | "number" | "date" | "boolean" | "array" | "object";
            /**
             * @description **Opzionale dalla 0.7.0.** La lingua e' una proprieta' della foglia (`lingue`), non del singolo campo: una foglia dichiara un contratto campi solo, che vale per tutte le lingue che dichiara. Indicate `lingua` su un campo solo se quel campo esiste in una lingua sola, e allora vale come restrizione. Fino alla 0.6.0 era obbligatoria su ogni campo, e un albero che la ometteva risultava interamente non conforme. E' un rilassamento: ogni albero valido con la 0.6.0 resta valido, nessuna integrazione deve cambiare nulla.
             * @enum {string|null}
             */
            lingua?: "IT" | "EN" | null;
            obbligatorio: boolean;
            ordine: number;
            descrizione?: string | null;
            /** @description Vincoli semplici (es. `minLength`, `minimum`) oppure, per un campo dipendente da un attributo profilo, un riferimento simbolico invece di un elenco statico: `{"fonte_opzioni": "profilo.<nome_attributo>", "default": "profilo.<nome_attributo>_base"}`, risolto da GEMODO contro il profilo scelto in fase di creazione modello. */
            validazione?: Record<string, never> | null;
        };
        StrutturaTipoDocumento: {
            /**
             * Format: date-time
             * @description Data/ora fornita dal sistema esterno, mostrabile come metadato. Nel servizio attuale varia a ogni richiesta: non e' una versione affidabile del catalogo ed e' esclusa dalle firme di compatibilita'.
             */
            validita: string;
            /** @description Primo livello dell'albero di categorizzazione di questo tipo documento. */
            nodi: components["schemas"]["NodoCategorizzazione"][];
        };
    };
    responses: {
        /** @description JWT assente o non valido */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "codice": "ACCESSO_NON_AUTENTICATO",
                 *       "messaggio": "Autenticazione richiesta"
                 *     }
                 */
                "application/json": components["schemas"]["Errore"];
            };
        };
        /** @description Ruolo/contesto non autorizzato (mai sull'unione dei contesti del token) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "codice": "ACCESSO_NON_AUTORIZZATO",
                 *       "messaggio": "Operazione non autorizzata"
                 *     }
                 */
                "application/json": components["schemas"]["Errore"];
            };
        };
        /** @description Modello/versione inesistente, tipo documento non trovato, o ramo non piu' disponibile in discovery */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Errore"];
            };
        };
        /** @description Integrazione non connessa, tipo documento gia' di un'altra integrazione o transizione di stato non valida */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Errore"];
            };
        };
        /** @description Selezione percorso/categoria incoerente o campi non ammessi/duplicati */
        InvalidInput: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Errore"];
            };
        };
        /** @description Discovery non raggiungibile o non conforme */
        SourceError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Errore"];
            };
        };
        /** @description Budget discovery scaduto */
        SourceTimeout: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "codice": "DISCOVERY_TIMEOUT",
                 *       "messaggio": "Tempo disponibile per discovery scaduto"
                 *     }
                 */
                "application/json": components["schemas"]["Errore"];
            };
        };
    };
    parameters: {
        CodiceTipoDocumento: string;
        ModelloId: string;
        VersioneId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listaContestiBuilder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contesti con permesso gestore derivato separatamente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       "geban"
                     *     ]
                     */
                    "application/json": string[];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getStrutturaDisponibile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codiceTipoDocumento: components["parameters"]["CodiceTipoDocumento"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Albero discovery corrente del tipo documento */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrutturaTipoDocumento"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            502: components["responses"]["SourceError"];
            504: components["responses"]["SourceTimeout"];
        };
    };
    listaModelliBuilder: {
        parameters: {
            query: {
                codice_contesto: string;
                offset?: number;
                limit?: number;
                codice_tipo_documento?: string;
                integrazione_id?: string;
                codice_tipologia?: string;
                codice_categoria?: string;
                lingua?: "IT" | "EN";
                /** @description Il token TUTTI seleziona i modelli senza livello, dove la colonna e' nulla. */
                livello_professionale?: string;
                variante?: string;
                /** @description Seleziona i modelli che hanno almeno una versione in questo stato. */
                stato_versione?: "BOZZA" | "IN_REVISIONE" | "APPROVATO" | "PUBBLICATO" | "ARCHIVIATO" | "SOSPESO";
                /** @description Sottostringa su nome e codice, applicata prima della paginazione. Usa ILIKE e non un indice: adeguata a modelli nell'ordine delle centinaia, da rivedere se crescessero di ordini di grandezza. */
                ricerca?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pagina modelli filtrata, vuota se nessun modello corrisponde */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example [] */
                    "application/json": components["schemas"]["ModelloGestione"][];
                };
            };
            400: components["responses"]["InvalidInput"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    creaModello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "codice_tipo_documento": "BANDO_CONCORSO",
                 *       "integrazione_id": "00000000-0000-0000-0000-000000000001",
                 *       "percorso_categorizzazione": [
                 *         "TD",
                 *         "RICERCATORE"
                 *       ],
                 *       "livello_professionale": "VI",
                 *       "lingua": "IT"
                 *     }
                 */
                "application/json": components["schemas"]["CreaModelloRequest"];
            };
        };
        responses: {
            /** @description Modello creato in stato BOZZA (senza ancora una versione) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Modello"];
                };
            };
            400: components["responses"]["InvalidInput"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getPolicyDimensioni: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codiceTipoDocumento: components["parameters"]["CodiceTipoDocumento"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Policy del tipo documento */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyDimensioni"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    setPolicyDimensione: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codiceTipoDocumento: components["parameters"]["CodiceTipoDocumento"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyDimensioneRequest"];
            };
        };
        responses: {
            /** @description Policy registrata o aggiornata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyDimensione"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description La dimensione non puo' ammettere un valore generico */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "codice": "GENERICO_NON_SUPPORTATO",
                     *       "messaggio": "La dimensione 'lingua' non puo' ammettere un valore generico"
                     *     }
                     */
                    "application/json": components["schemas"]["Errore"];
                };
            };
        };
    };
    vociFiltriModelli: {
        parameters: {
            query: {
                codice_contesto: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Voci selezionabili, liste vuote se il contesto non ha modelli */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VociFiltriModelli"];
                };
            };
            400: components["responses"]["InvalidInput"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getModelloDettaglio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelloId: components["parameters"]["ModelloId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Modello con versioni e campi del contratto */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelloDettaglio"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    eliminaModello: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelloId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Modello eliminato, versioni pubblicate archiviate */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    creaVariante: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelloId: components["parameters"]["ModelloId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "nota": "Senza prova preselettiva"
                 *     }
                 */
                "application/json": components["schemas"]["CreaVarianteRequest"];
            };
        };
        responses: {
            /** @description Variante creata, senza versioni */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelloGestione"];
                };
            };
            400: components["responses"]["InvalidInput"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    creaEdizioneDerivata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelloId: components["parameters"]["ModelloId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "lingua": "EN"
                 *     }
                 */
                "application/json": components["schemas"]["CreaEdizioneDerivataRequest"];
            };
        };
        responses: {
            /** @description Modello derivato e versione 1 BOZZA creati */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelloGestione"];
                };
            };
            400: components["responses"]["InvalidInput"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    creaVersione: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelloId: components["parameters"]["ModelloId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "campi": [
                 *         {
                 *           "codice": "codice_bando",
                 *           "lingua": "IT"
                 *         },
                 *         {
                 *           "codice": "titolo_it",
                 *           "lingua": "IT"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["CreaVersioneRequest"];
            };
        };
        responses: {
            /** @description Versione creata in stato BOZZA */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Versione"];
                };
            };
            400: components["responses"]["InvalidInput"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    inviaRevisione: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelloId: components["parameters"]["ModelloId"];
                versioneId: components["parameters"]["VersioneId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versione in stato IN_REVISIONE */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Versione"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    approvaVersione: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelloId: components["parameters"]["ModelloId"];
                versioneId: components["parameters"]["VersioneId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versione in stato APPROVATO */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Versione"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    pubblicaVersione: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelloId: components["parameters"]["ModelloId"];
                versioneId: components["parameters"]["VersioneId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versione in stato PUBBLICATO, ora esposta dal catalogo (001) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Versione"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    sospendiVersione: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelloId: components["parameters"]["ModelloId"];
                versioneId: components["parameters"]["VersioneId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versione in stato SOSPESO */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Versione"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    archiviaVersione: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelloId: components["parameters"]["ModelloId"];
                versioneId: components["parameters"]["VersioneId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versione in stato ARCHIVIATO */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Versione"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
}
